In [1]:
import numpy as np

In [2]:
import statsmodels.api as sm

In [47]:
from sklearn.datasets import make_regression
X, y = make_regression(n_samples=1000, n_features=10, n_informative=10, noise=12)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [48]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [49]:
model.coef_

array([94.71137863, 41.12924298, 41.32566938,  8.86170058, 85.19902307,
       23.05942546, 25.57344218, 37.58621284, 46.76620803, 88.25308256])

In [50]:
model.intercept_

0.2536824003223046

In [51]:
y_pred = model.predict(X_test)

# R2 

Коэффициент детерминации - Статистика **R-квадрат** варьирует в интервале от 0 до 1 и измеряет долю вариации в данных, объясняемую в модели.\
Знаменатель TSS - пропорционален дисперсии отклика($y$)

$$
R^2 = 1 - \frac{RSS}{TSS}
$$
$RSS$ - Остаточная сумма квадратов \
$TSS$ - Общая сумма квадратов

$$
RSS = \sum{(y_{true}-y_{pred})^2}
$$

$$
TSS = \sum(y_{true}-\bar{y_{true}})
$$

$\bar{y_{true}}$ - Среднее значение $y$

In [52]:
from sklearn.metrics import r2_score

In [53]:
r2_score(y_test, y_pred)

0.9962898731604424

In [67]:
RSS = np.sum((y_test - y_pred)**2)
RSS

33492.31479853841

In [68]:
TSS = np.sum((y_test - np.mean(y_test))**2)
TSS

9027269.483469184

In [72]:
1-RSS/TSS

0.9962898731604424

In [80]:
TSS/np.var(y_test)

250.0

# F-statistic

значения F-статистики (чем выше — тем важнее признак)

In [82]:
from sklearn.feature_selection import SelectKBest, f_regression

In [83]:
selector = SelectKBest(score_func=f_regression, k='all')
selector.fit(X, y)

SelectKBest(k='all', score_func=<function f_regression at 0x0000017E43B514E0>)

In [86]:
selector.scores_

array([367.76570655,  44.96309098,  44.03733836,   2.60812188,
       257.63667703,  16.60489204,  16.2760199 ,  47.11352627,
        48.18683606, 413.20376485])

In [84]:
selector.pvalues_

array([5.00509456e-70, 3.35548381e-11, 5.27643363e-11, 1.06633688e-01,
       9.49588456e-52, 4.96865908e-05, 5.89324902e-05, 1.17513149e-11,
       6.96881213e-12, 3.87974030e-77])

# t-statistic

----

# AIC, BIC, AICc, CP

167

In [90]:
from dmba import adjusted_r2_score, AIC_score, BIC_score, stepwise_selection, forward_selection, backward_elimination

Взвешенная

In [21]:
import pandas as pd
# pd.get_dummies()
# pd.cut()
# pd.concat()
df = pd.DataFrame({'One':[1,2,3,4,5], 'Two':[1,2,3,4,5]})

# Поменять местами столбцы
df = df.assign(const=1)
const = df['const']
df = df.drop('const', axis=1)
df.insert(0, 'const', const)
df

const  One  Two
0      1    1    1
1      1    2    2
2      1    3    3
3      1    4    4
4      1    5    5

In [22]:
df.values

array([[1, 1, 1],
       [1, 2, 2],
       [1, 3, 3],
       [1, 4, 4],
       [1, 5, 5]], dtype=int64)