# Статистика

**`Коэффициент вариации`** - Относительную изменчивость данных в наборах данных с разными масштабами.
$$
КВ = \frac{s}{\mu}
$$
$s$ - Стандартное отклонение\
$\mu$ - Среднее арифметическое

In [8]:
import numpy as np
cm = np.array([180, 190, 195]) # Рост в см
inch = np.array([70.8661, 74.8031, 76.7717]) # Тот же рост в дюймах

In [11]:
np.std(cm)/np.mean(cm), np.std(inch)/np.mean(inch)

(0.03311201227233576, 0.03311243332922641)

In [13]:
from scipy.stats import variation
variation(cm), variation(inch)

(0.03311201227233576, 0.03311243332922641)

# Дифференцирование

`Ассимптота` : Это прямая, к которой приближается график функции, но никогда не пересекает её. \
`lim` : 

`Производная` : Скорость изменения функции одной переменной в конкретной точке. Как сильно изменяется значение функции $y$ от изменения аргумента $x$.
$$
f'(x) = \frac{\partial f}{\partial x}
$$
Любая производная вычисляется по формуле.
$$
f'(x) = n*x^{n-1}
$$
**Геометрический смысл производной**: Производная функции в точке равна угловому коэффиенту касательной проведенной через эту точку, угловой коэффицент $k$ равен тангенсу, то есть отношение противлежащего катета к прилежащему это и будет значение производной данной функции. Семантически это даже не касательная а секущая, прямая линия построенная по двум точкам, $x$ и $dx$, только в качестве $dx$ взята точка стремящаяся к $x$ ($lim->x$) поэтому разница между $x$ и $dx$ в пределе стремится к нулю, поэтому секущая сводится к касательной.


`Экстремум` : Такое значение $x$ при котором функция становится максимально или минимально возможной среди всех блихлежащих точек. Производная функции в этой точке равна нулю. *Функция меняет свое направление*
Локальный экстремум - Минимум или максимум функции в локальной области. \
Глобальный экстремум - Наибольшее или наименьшее значение функции, которое возможно у всей функции. \

`Частная производная` : Производная функции нескольких переменных по одной из этих переменных. Все остальные переменные фиксируются как константы

`Градиент` : Вектор частных производных по каждому аргументу

# Линейная алгебра

**`Длина вектора`** : Сумма квадратов из всех его компонент(Гипотенуза в теореме Пифагора)
$$
|| \vec{v} \| = \sqrt{v_1^2 + v_2^2 + \dots + v_n^2}
$$

-----
**`Скалярное произведение`** : Сумма произведений соответствующих компонент вектора. Сумма покомпонетных умножений.\
a = x1, x2, x3 (Первый вектор)\
b = y1, y2, y3 (Второй вектор)\
$a * b = x1*y1 + x2*y2 + x3*y3$

$$
\vec{a}*\vec{b} = \sum{{a_i}*{b_i}}
$$


----
**`Матричное произведение`** : Умножение матриц.\
Обязательное условие, чтобы количество столбцов в матрице $A$ равнялось количеству строк в матрице $B$.\
В таком случаи результатом умножения матрицы $A (n*m)$ на матрицу $B (m*p)$ будет являться матрица $C (n*p)$\
Каждый элемент матрицы $C$ рассчитывается как скалярное произведение соответствующих строк матрицы $A$ и столбцов матрицы $B$.

$$
C_{ij} = \sum{A_{ik}*{B_{kj}}}
$$

In [18]:
import numpy as np
np.random.seed(10)
A = np.random.randint(2, 6, size=(3, 2))
B = np.random.randint(1, 5, size=(2, 3))
print('Матрица А(3,2)')
print(A)
print()
print('Матрица B(2,3)')
print(B)

Матрица А(3,2)
[[3 3]
 [2 5]
 [2 3]]

Матрица B(2,3)
[[4 1 2]
 [2 1 2]]


In [22]:
A @ B

array([[18,  6, 12],
       [18,  7, 14],
       [14,  5, 10]])

In [23]:
np.dot(A, B)

array([[18,  6, 12],
       [18,  7, 14],
       [14,  5, 10]])

In [24]:
np.matmul(A, B)

array([[18,  6, 12],
       [18,  7, 14],
       [14,  5, 10]])

-----
**`Транспонированная матрица`** - Матрица у которой столбцы и строки поменяны местами
$$
A^T
$$

In [56]:
A = np.random.randint(2, 8, size=(2, 3))
print(f'Исходная матрица:')
print(A)

Исходная матрица:
[[2 6 3]
 [5 2 3]]


In [57]:
print(f'Транспонированная матрица:')
print(A.T)

Транспонированная матрица:
[[2 5]
 [6 2]
 [3 3]]


**`Обратная матрица`** - Матрица существующая только для квадратной матрицы. Такая матрица при умножении на которую исходной квадратной матрицы в результате получается **единичная матрица**\
**`Единичная матрица`** - Квадратная матрица у которой все элементы на главной диагонали - единицы, а все остальные - нули.

$$
A^{-1}
$$
$$
AA^{-1} = I
$$
$A$ - Квадратная матрица\
$A^{-1}$ - Обратная матрица\
$I$ - Единичная матрица

In [58]:
A = np.random.randint(2, 8, size=(3, 3))

print(f'Исходная квадратная матрица:')
print(A)

Исходная квадратная матрица:
[[6 3 3]
 [3 2 6]
 [4 7 4]]


In [59]:
invA = np.linalg.inv(A)

print(f'Обратная матрица:')
print(invA)

Обратная матрица:
[[ 0.26356589 -0.06976744 -0.09302326]
 [-0.09302326 -0.09302326  0.20930233]
 [-0.10077519  0.23255814 -0.02325581]]


In [60]:
I = invA @ A
I = I.round()

print(f'Единичная матрица:')
print(I)

Единичная матрица:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0. -0.  1.]]


**`Диагональная матрица`** - Матрица у которой все значения кроме главной диагонали равны нулю. Её можно сконстрировать из вектора.

In [68]:
vec = np.random.randint(1, 5, size=5)
diag = np.diag(vec)
print('Исходный вектор')
print(vec)
print('Диагональная матрица')
print(diag)

Исходный вектор
[3 3 1 4 3]
Диагональная матрица
[[3 0 0 0 0]
 [0 3 0 0 0]
 [0 0 1 0 0]
 [0 0 0 4 0]
 [0 0 0 0 3]]


**`Ортнормальная матрица`** - или **Ортогональная** если она вещественная(в ней отсутствуют комплексные числа). Матрица $Q$ ортнормальная если Q-транспонированная равна Q-обратной.\
т.е.
- Вектор-столбцы и вектор-строки взаимно ортоганальны
- И нормированы. Длина каждого вектора равна единице.

$$
Q^TQ=I
$$
$$
Q^{-1}=Q^T
$$

**`Ранк`** - Количество линейно независимых строк(или столбцов). Нельзя получить строку в матрице комбинацией или произведением из другой строки.

In [84]:
A = np.array([[1, 2, 3], 
              [2, 4, 6],
              [7, 8, 9]])
A

array([[1, 2, 3],
       [2, 4, 6],
       [7, 8, 9]])

In [85]:
rank_A = np.linalg.matrix_rank(A)
print('Ранг матрицы:', rank_A)


Ранг матрицы: 2


**`Выражденная матрица`** - Матрица у которой **Детерменант** равен нулю, что говорит о том, что у неё нет обратной матрицы, не имеет полной ранговой структуры и её столбцы или строки линейно зависимы


**`Детерминант`** - Коэффициент масштабируемости квадратной матрицы. То как матрица сжимает или растягивает пространство.\
Если детерменант равен 0 - матрица выражденная. Объекты теряют размерность.\
Если детерминант положительный - матрица растягивает пространство.
Если детерминант отрицательный - матрица растягивает пространство с изменением ориентации координат(например зеркальное отображение)


In [86]:
A

array([[1, 2, 3],
       [2, 4, 6],
       [7, 8, 9]])

In [92]:
np.linalg.det(A) # Выраждена

0.0

In [93]:
A2 = np.random.randint(1, 7, size=(3, 3))
A2

array([[3, 6, 1],
       [1, 6, 6],
       [5, 2, 4]])

In [94]:
np.linalg.det(A2) # Не выраждена

163.99999999999991