In [1]:
import numpy as np

In [6]:
np.array([[1,3], [1, 2]])
np

array([[1, 3],
       [1, 2]])

In [5]:
np.linalg.det
np.linalg.norm
np.linalg.matrix_rank

<function matrix_rank at 0x0000028F16E4A870>

In [48]:
np.random.randint(1, 2, size=3)
np.random.choice([1, 2, 3, 4], p=[0.1, 0.8, 0.1, 0])
np.random.rand(2, 2)
np.random.randn(2, 1)
np.random.random((2,1))

np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [68]:
np.concatenate([np.array([3, 1, 2]), np.array([2, 3,4])])
np.c_[np.array([1,2,3]), np.array([4,5,6])]
np.stack()
np.vstack()
np.hstack()

TypeError: stack() missing 1 required positional argument: 'arrays'

In [69]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])