In [2]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

In [3]:
x, y = sp.symbols('x y')

In [4]:
y = 1+x**2/2

In [5]:
y

x**2/2 + 1

In [61]:
sp.diff(y)

x

In [62]:
y.subs({x:2})

3

In [63]:
from sympy import symbols, Eq, solve

In [64]:
# уравнение
x, y = sp.symbols('x y')
equation = Eq(x**2, -4)

In [65]:
equation

Eq(x**2, -4)

In [66]:
s = solve(equation, x)

In [67]:
s

[-2*I, 2*I]

In [68]:
# система уравнений
x, y, z = sp.symbols('x y z')
system = [Eq(x+y+z, 1),
          Eq(x-y-z, 0),
          Eq(x**2+y**2+z, 1)]

In [69]:
solve(system, (x, y, z))

[(1/2, 1/2 - sqrt(2)/2, sqrt(2)/2), (1/2, 1/2 + sqrt(2)/2, -sqrt(2)/2)]

In [72]:
# Матрицы
from sympy import Matrix

In [71]:
a, b, c, d = sp.symbols('a b c d')

In [73]:
matr = Matrix([[a, b], [c, d]])

In [74]:
matr

Matrix([
[a, b],
[c, d]])

In [75]:
matr_2 = Matrix([[1, 2], [3, 4])

In [76]:
matr+matr_2

Matrix([
[a + 1, b + 2],
[c + 3, d + 4]])

In [77]:
vec = Matrix([1, 2])

In [83]:
vec

Matrix([
[1],
[2]])

In [80]:
matr_2

Matrix([
[1, 2],
[3, 4]])

In [82]:
matr_2 * vec

Matrix([
[ 5],
[11]])

In [85]:
matr*matr_2

Matrix([
[a + 3*b, 2*a + 4*b],
[c + 3*d, 2*c + 4*d]])

In [86]:
# lambdify

In [88]:
x, y = sp.symbols('x y')

In [89]:
y = x**2

In [90]:
y

x**2

In [92]:
f = sp.lambdify(x, y, 'numpy')

In [93]:
f

<function _lambdifygenerated(x)>

In [95]:
f(2)

4

In [96]:
f(3)

9

In [97]:
X = np.array([1, 2, 3])

In [98]:
X

array([1, 2, 3])

In [101]:
f(X)

array([1, 4, 9])

In [140]:
# -
y, y_pred, n = sp.symbols('y y_pred n')

In [143]:
mse = (y-y_pred)**2/n

In [144]:
mse

(y - y_pred)**2/n

In [147]:
dmse = sp.lambdify([y, y_pred], mse, 'numpy')

In [151]:
dmse(5, 2)

9/n

In [158]:
np_expr = 'np.sin(x)+np.cos(x)'
sp_expr = sp.sympify(np_expr, locals={'np':sp})

In [159]:
sp_expr

sin(x) + cos(x)

In [194]:
from autograd import grad
import autograd.numpy as anp

In [219]:
y = np.array([2, 3, 4])
y_pred = np.array([4, 6, 8])
def loss(y, y_pred):
    return anp.mean((y - y_pred)**2)
    
grad_loss = grad(loss, 1)
gradient = grad_loss(y, y_pred)
gradient

array([1.33333333, 2.        , 2.66666667])

In [220]:
def gr_mserror(y, y_pred):
    return np.array([2/len(X)*np.sum((y - y_pred)) * (-1)])

In [221]:
gr_mserror(y[2], y_pred[2])

array([2.66666667])

In [2]:
x, y = sp.symbols('x y')

In [4]:
y = sp.cos(x)

In [5]:
sp.diff(y)

-sin(x)

In [6]:
y = x**2

In [7]:
x**2

x**2

In [9]:
sp.diff(x**2)

2*x

$x^2$

$\frac{2}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i) \cdot (-1)$